package mx.edu.itszapopan.bolsatrabajo.VO;
// Generated 14/09/2017 08:24:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CareerInstituteId generated by hbm2java
 */
@Embeddable
public class CareerInstituteId  implements java.io.Serializable {


     private int idCareer;
     private int idInstitute;

    public CareerInstituteId() {
    }

    public CareerInstituteId(int idCareer, int idInstitute) {
       this.idCareer = idCareer;
       this.idInstitute = idInstitute;
    }
   


    @Column(name="idCareer", nullable=false)
    public int getIdCareer() {
        return this.idCareer;
    }
    
    public void setIdCareer(int idCareer) {
        this.idCareer = idCareer;
    }


    @Column(name="idInstitute", nullable=false)
    public int getIdInstitute() {
        return this.idInstitute;
    }
    
    public void setIdInstitute(int idInstitute) {
        this.idInstitute = idInstitute;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CareerInstituteId) ) return false;
		 CareerInstituteId castOther = ( CareerInstituteId ) other; 
         
		 return (this.getIdCareer()==castOther.getIdCareer())
 && (this.getIdInstitute()==castOther.getIdInstitute());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCareer();
         result = 37 * result + this.getIdInstitute();
         return result;
   }   


}


