package mx.edu.itszapopan.bolsatrabajo.VO;
// Generated 14/09/2017 08:24:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Career generated by hbm2java
 */
@Entity
@Table(name="Career"
    ,catalog="bolsa_trabajo"
)
public class Career  implements java.io.Serializable {


     private Integer idCareer;
     private String name;
     private Set<Vacancy> vacancies = new HashSet<Vacancy>(0);
     private Set<Student> students = new HashSet<Student>(0);
     private Set<CareerInstitute> careerInstitutes = new HashSet<CareerInstitute>(0);

    public Career() {
    }

	
    public Career(String name) {
        this.name = name;
    }
    public Career(String name, Set<Vacancy> vacancies, Set<Student> students, Set<CareerInstitute> careerInstitutes) {
       this.name = name;
       this.vacancies = vacancies;
       this.students = students;
       this.careerInstitutes = careerInstitutes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCareer", unique=true, nullable=false)
    public Integer getIdCareer() {
        return this.idCareer;
    }
    
    public void setIdCareer(Integer idCareer) {
        this.idCareer = idCareer;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="career")
    public Set<Vacancy> getVacancies() {
        return this.vacancies;
    }
    
    public void setVacancies(Set<Vacancy> vacancies) {
        this.vacancies = vacancies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="career")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="career")
    public Set<CareerInstitute> getCareerInstitutes() {
        return this.careerInstitutes;
    }
    
    public void setCareerInstitutes(Set<CareerInstitute> careerInstitutes) {
        this.careerInstitutes = careerInstitutes;
    }




}


