package mx.edu.itszapopan.bolsatrabajo.VO;
// Generated 14/09/2017 08:24:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Curriculum generated by hbm2java
 */
@Entity
@Table(name="Curriculum"
    ,catalog="bolsa_trabajo"
    , uniqueConstraints = @UniqueConstraint(columnNames="idStudent") 
)
public class Curriculum  implements java.io.Serializable {


     private Integer idCurriculum;
     private Student student;
     private String goals;
     private String knowledge;
     private String experience;

    public Curriculum() {
    }

    public Curriculum(Student student, String goals, String knowledge, String experience) {
       this.student = student;
       this.goals = goals;
       this.knowledge = knowledge;
       this.experience = experience;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCurriculum", unique=true, nullable=false)
    public Integer getIdCurriculum() {
        return this.idCurriculum;
    }
    
    public void setIdCurriculum(Integer idCurriculum) {
        this.idCurriculum = idCurriculum;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idStudent", unique=true)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="goals", length=45)
    public String getGoals() {
        return this.goals;
    }
    
    public void setGoals(String goals) {
        this.goals = goals;
    }

    
    @Column(name="knowledge", length=45)
    public String getKnowledge() {
        return this.knowledge;
    }
    
    public void setKnowledge(String knowledge) {
        this.knowledge = knowledge;
    }

    
    @Column(name="experience", length=45)
    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }




}


