package mx.edu.itszapopan.bolsatrabajo.VO;
// Generated 14/09/2017 08:24:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DocumentData generated by hbm2java
 */
@Entity
@Table(name="DocumentData"
    ,catalog="bolsa_trabajo"
    , uniqueConstraints = @UniqueConstraint(columnNames="idDocumentType") 
)
public class DocumentData  implements java.io.Serializable {


     private Integer idDocumentData;
     private DocumentType documentType;
     private Student student;
     private String name;
     private Set<File> files = new HashSet<File>(0);

    public DocumentData() {
    }

	
    public DocumentData(DocumentType documentType, Student student) {
        this.documentType = documentType;
        this.student = student;
    }
    public DocumentData(DocumentType documentType, Student student, String name, Set<File> files) {
       this.documentType = documentType;
       this.student = student;
       this.name = name;
       this.files = files;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDocumentData", unique=true, nullable=false)
    public Integer getIdDocumentData() {
        return this.idDocumentData;
    }
    
    public void setIdDocumentData(Integer idDocumentData) {
        this.idDocumentData = idDocumentData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDocumentType", unique=true, nullable=false)
    public DocumentType getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idStudent", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="documentData")
    public Set<File> getFiles() {
        return this.files;
    }
    
    public void setFiles(Set<File> files) {
        this.files = files;
    }




}


