package mx.edu.itszapopan.bolsatrabajo.VO;
// Generated 14/09/2017 08:24:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Institute generated by hbm2java
 */
@Entity
@Table(name="Institute"
    ,catalog="bolsa_trabajo"
)
public class Institute  implements java.io.Serializable {


     private Integer idInstitute;
     private String name;
     private Set<Student> students = new HashSet<Student>(0);
     private Set<CareerInstitute> careerInstitutes = new HashSet<CareerInstitute>(0);

    public Institute() {
    }

	
    public Institute(String name) {
        this.name = name;
    }
    public Institute(String name, Set<Student> students, Set<CareerInstitute> careerInstitutes) {
       this.name = name;
       this.students = students;
       this.careerInstitutes = careerInstitutes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idInstitute", unique=true, nullable=false)
    public Integer getIdInstitute() {
        return this.idInstitute;
    }
    
    public void setIdInstitute(Integer idInstitute) {
        this.idInstitute = idInstitute;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="institute")
    public Set<Student> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<Student> students) {
        this.students = students;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="institute")
    public Set<CareerInstitute> getCareerInstitutes() {
        return this.careerInstitutes;
    }
    
    public void setCareerInstitutes(Set<CareerInstitute> careerInstitutes) {
        this.careerInstitutes = careerInstitutes;
    }




}


