package mx.edu.itszapopan.bolsatrabajo.VO;
// Generated 14/09/2017 08:24:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name="Job"
    ,catalog="bolsa_trabajo"
)
public class Job  implements java.io.Serializable {


     private Integer idJob;
     private Student student;
     private String jobTitle;
     private String company;
     private String time;

    public Job() {
    }

    public Job(Student student, String jobTitle, String company, String time) {
       this.student = student;
       this.jobTitle = jobTitle;
       this.company = company;
       this.time = time;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idJob", unique=true, nullable=false)
    public Integer getIdJob() {
        return this.idJob;
    }
    
    public void setIdJob(Integer idJob) {
        this.idJob = idJob;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idStudent", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="jobTitle", nullable=false, length=45)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="company", nullable=false, length=45)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="time", nullable=false, length=45)
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }




}


